import { SceneObject } from '../components/onboarding-coordinator/onboarding-types';

export const BOB: SceneObject[] = [
  { wizardStep: 0, questionID: 'email_signin' },
  { wizardStep: 1, questionID: 'email_verification' },
  {
    wizardStep: 2,
    questionID: '111',
    title: {
      id: '1',
      textType: 'headerMedium1',
      text: 'At Upward Running and Walking we equip everyone, regardless of where you are starting.',
    },
    textFields: [
      {
        order: 1,
        id: '001',
        textType: 'bodyMedium1',
        text: 'Which statement best describes you today?',
      },
    ],
    required: false,
    questionType: 'single-select',
    options: [
      {
        id: '001',
        isSelected: false,
        text: {
          order: 1,
          id: '001',
          textType: 'bodyMedium1',
          text: 'I want to become a walker',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '002',
        isSelected: false,
        text: {
          order: 2,
          id: '002',
          textType: 'bodyMedium1',
          text: 'I want to become a runner',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '003',
        isSelected: false,
        text: {
          order: 3,
          id: '003',
          textType: 'bodyMedium1',
          text: 'I am a walker',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '004',
        isSelected: false,
        text: {
          order: 4,
          id: '004',
          textType: 'bodyMedium1',
          text: 'I am a runner',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
    ],
  },
  {
    wizardStep: 3,
    questionID: '112',
    title: {
      id: '1',
      textType: 'headerBold1',
      text: 'Congratulations!',
    },
    textFields: [
      {
        order: 1,
        id: '001',
        textType: 'bodyMedium1',
        text: 'Based on the information you have provided, we suggest you enroll in a one of the programs below.',
      },
    ],
    required: false,
    questionType: 'carousel',
    options: [
      {
        id: '001',
        isSelected: false,
        text: {
          order: 1,
          id: '001',
          textType: 'bodyMedium1',
          text: 'Select this plan',
        },
        planInformation: {
          title: {
            order: 1,
            id: '001',
            textType: 'bodyMedium1',
            text: 'Couch to 5k Walker Training Plan',
          },
          skillLevel: {
            // order: 1,
            // id: '001',
            // textType: 'bodyMedium2',
            // text: '(Beginner)',
          },
          details: [
            // {
            //   order: 1,
            //   id: '001',
            //   textType: 'bodyMedium3',
            //   text: 'Start anytime',
            // },
            // {
            //   order: 2,
            //   id: '002',
            //   textType: 'bodyMedium3',
            //   text: '12 week duration',
            // },
            // {
            //   order: 3,
            //   id: '003',
            //   textType: 'bodyMedium3',
            //   text: 'Self Paced',
            // },
          ],
          startDateInformation: {
            // id: '001',
            // textType: 'bodyMedium3',
            // text: 'Starts Aug 4, 2024',
          },
          description: {
            order: 1,
            id: '001',
            textType: 'bodyRegular1',
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean bibendum enim elit, sed ullamcorper velit auctor vel. Donec viverra, ipsum eget condimentum sollicitudin, lorem lacus.',
          },
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '002',
        isSelected: false,
        text: {
          order: 1,
          id: '002',
          textType: 'bodyMedium1',
          text: 'Select this plan',
        },
        planInformation: {
          title: {
            order: 1,
            id: '001',
            textType: 'bodyMedium1',
            text: 'Couch to 10k Walker Training Plan',
          },
          skillLevel: {
            order: 1,
            id: '001',
            textType: 'bodyMedium2',
            text: '(Beginner)',
          },
          details: [
            {
              order: 1,
              id: '001',
              textType: 'bodyMedium3',
              text: 'Start anytime',
            },
            {
              order: 2,
              id: '002',
              textType: 'bodyMedium3',
              text: '12 week duration',
            },
            {
              order: 3,
              id: '003',
              textType: 'bodyMedium3',
              text: 'Self Paced',
            },
          ],
          startDateInformation: {
            id: '001',
            textType: 'bodyMedium3',
            text: 'Starts March 4, 2024 (already started)',
          },
          description: {
            order: 1,
            id: '001',
            textType: 'bodyRegular1',
            text: 'This plan will test you to the max and you are gonna be hatin life when you finish.',
          },
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
    ],
  },
  {
    wizardStep: 4,
    questionID: '112',
    title: {
      id: '1',
      textType: 'headerBold1',
      text: 'Choose a Start Date',
    },
    textFields: [
      {
        order: 1,
        id: '001',
        textType: 'bodyMedium1',
        text: 'Choose which Monday you would like to start on. If you plan to run in a race, enter the race date and we will automatically calculate the best date to start on.',
      },
    ],
    required: false,
    questionType: 'startdate_select',
    options: [
      {
        id: '001',
        isSelected: false,
        text: {
          order: 1,
          id: '001',
          textType: 'bodyMedium1',
          text: 'I am training for a race',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '002',
        isSelected: false,
        text: {
          order: 2,
          id: '002',
          textType: 'bodyMedium1',
          text: 'Enter Race Date:',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
    ],
  },
  {
    wizardStep: 5,
    questionID: '333',
    title: {
      id: '3',
      textType: 'bodyBold1',
      text: 'There is so much to learn about how to properly and safely train in this sport. We will equip you weekly with tips, tricks, best practices, and at times in depth training philosophy. To help get us started, how would you describe your knowledge base in the sport?',
    },
    textFields: [],
    required: false,
    questionType: 'single-select',
    options: [
      {
        id: '001',
        isSelected: false,
        text: {
          order: 1,
          id: '001',
          textType: 'bodyMedium1',
          text: 'Assume I know nothing, give me the basics.',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '002',
        isSelected: false,
        text: {
          order: 2,
          id: '002',
          textType: 'bodyMedium1',
          text: 'Only what Google has told me',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '003',
        isSelected: false,
        text: {
          order: 3,
          id: '003',
          textType: 'bodyMedium1',
          text: 'I know more than my friends but still need to learn more.',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '004',
        isSelected: false,
        text: {
          order: 4,
          id: '004',
          textType: 'bodyMedium1',
          text: 'I know enough to be dangerous.',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '005',
        isSelected: false,
        text: {
          order: 4,
          id: '004',
          textType: 'bodyMedium1',
          text: "I'm pretty sure I know everything but try me.",
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '006',
        isSelected: false,
        text: {
          order: 4,
          id: '004',
          textType: 'bodyMedium1',
          text: 'My knowledge is very extensive.',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
    ],
  },
  {
    wizardStep: 6,
    questionID: '333',
    title: {
      id: '3',
      textType: 'bodyBold1',
      text: 'In addition to improving your fitness we want to see you grow as a person. Choose a personal growth plan for the next 12 weeks.',
    },
    textFields: [
      {
        order: 1,
        id: '004',
        textType: 'bodyMedium1',
        text: 'View all Growth Plans',
      },
    ],
    required: false,
    questionType: 'single-select',
    options: [
      {
        id: '001',
        isSelected: false,
        text: {
          order: 1,
          id: '001',
          textType: 'bodyMedium1',
          text: 'I want to be a better person',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '002',
        isSelected: false,
        text: {
          order: 2,
          id: '002',
          textType: 'bodyMedium1',
          text: 'A walk thru James',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
      {
        id: '003',
        isSelected: false,
        text: {
          order: 3,
          id: '003',
          textType: 'bodyMedium1',
          text: 'Seminary, here I come',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'hi bob',
      },
    ],
  },
  {
    wizardStep: 7,
    questionID: '555',
    title: {
      id: '3',
      textType: 'headerBold1',
      text: 'Choose a group',
    },
    textFields: [
      {
        order: 1,
        id: '004',
        textType: 'bodyMedium1',
        text: "Select on or more groups to participate in. Don't worry, you can always add or change groups later.",
      },
    ],
    required: false,
    questionType: 'social-select',
    options: [
      {
        id: '001',
        isSelected: false,
        image: `https://picsum.photos/400/300?t=${new Date().getTime()}`,
        text: {
          order: 1,
          id: '001',
          textType: 'bodyMedium1',
          text: 'National Group',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'This group has all the cool kids.',
      },
      {
        id: '002',
        isSelected: false,
        image: `https://picsum.photos/400/300?t=${new Date().getTime()}`,
        text: {
          order: 2,
          id: '002',
          textType: 'bodyMedium1',
          text: 'Women Only',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'Only women will be presented this option.',
      },
      {
        id: '003',
        isSelected: false,
        image: `https://picsum.photos/400/300?t=${new Date().getTime()}`,
        text: {
          order: 3,
          id: '003',
          textType: 'bodyMedium1',
          text: 'Aging Gracefully',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'Get off my lawn.',
      },
    ],
  },
  {
    wizardStep: 8,
    questionID: '666',
    title: {
      id: '3',
      textType: 'headerMedium1',
      text: 'Hold tight while we finish getting things ready based on your selections',
    },
    textFields: [],
    required: false,
    questionType: 'finish',
    options: [
      {
        id: '001',
        isSelected: false,
        image: 'https://some/bucket/image',
        text: {
          order: 1,
          id: '001',
          textType: 'bodyMedium1',
          text: 'National Group',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'This group has all the cool kids.',
      },
      {
        id: '002',
        isSelected: false,
        image: 'https://some/bucket/image',
        text: {
          order: 2,
          id: '002',
          textType: 'bodyMedium1',
          text: 'Women Only',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'Only women will be presented this option.',
      },
      {
        id: '003',
        isSelected: false,
        image: 'https://some/bucket/image',
        text: {
          order: 3,
          id: '003',
          textType: 'bodyMedium1',
          text: 'Aging Gracefully',
        },
        nextStep: 'STEP_2',
        prevStep: 'STEP_1',
        tooltipText: 'Get off my lawn.',
      },
    ],
  },
];
