export const PREFERRED_COLOR_THEME_STORAGE_KEY = 'preferred_color_theme_id';
export const SERVER_TYPE_KEY = 'settings.server_type';
export const POST_DRAFT_PREFERENCES_STORAGE_KEY = 'POST_DRAFT_PREFERENCES_STORAGE_KEY';
export const POST_DRAFT_STORAGE_KEY = 'POST_DRAFT_STORAGE_KEY';
export const PERMANENT_STORAGE_KEY_WHITELIST = 'PERMANENT_STORAGE_KEY_WHITELIST';
export const QUOTE_USER_SESSION_INFO = 'QUOTE_USER_SESSION_INFO';
export const AGENT_PORTAL_SESSION_INFO = 'AGENT_PORTAL_SESSION_INFO';
export const USER_PRESENTED_NOTIFICATION = 'USER_PRESENTED_NOTIFICATION';
